print("Hi, student")
a=int(input("Enter the first number"))
b=int(input("Enter the second number"))
print("Summa is", a+b)
print("Multymultiplication", a/b)
name=input("Enter your name ")
print("Hi,", name)
